# Generated by Django 4.2.2 on 2023-07-10 00:26

import datetime
import devices.models
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(help_text='a globally unique ID for the device', verbose_name='device unique ID')),
                ('name', models.CharField(help_text='human friendly device name', max_length=32, verbose_name='device name')),
                ('is_active', models.BooleanField(default=True, help_text='is the device enabled', verbose_name='is device enabled')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, help_text='when was the device added to the system', verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='device group name')),
                ('description', models.TextField(blank=True, default='', max_length=256, verbose_name='device group description')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, help_text='when was the group first created', verbose_name='creation date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member', verbose_name='device group owner')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField(blank=True, default=devices.models.initialize_device_data, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='device data')),
                ('date', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, 1, tzinfo=datetime.timezone.utc), help_text='when was the data received', verbose_name='last update')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicegroup', verbose_name='device group'),
        ),
    ]
